/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#fff8f4',
        'surface-dim': '#e2d8d0',
        'surface-bright': '#fff8f4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fcf2ea',
        'surface-container': '#f7ece4',
        'surface-container-high': '#f1e6de',
        'surface-container-highest': '#ebe1d9',
        'on-surface': '#1f1b16',
        'on-surface-variant': '#41484c',
        'inverse-surface': '#352f2a',
        'inverse-on-surface': '#f9efe7',
        outline: '#72787d',
        'outline-variant': '#c1c7cd',
        'surface-tint': '#3a637b',
        primary: '#3a637b', /* Using surface-tint/primary-container as primary brand as per guide */
        'primary-text': '#204b62',
        'on-primary': '#ffffff',
        'primary-container': '#3a637b',
        'on-primary-container': '#b4defa',
        'inverse-primary': '#a3cce7',
        secondary: '#6c7b38', /* Using Ancient Olive Grove as per guide */
        'on-secondary': '#ffffff',
        'secondary-container': '#d9eb9b',
        'on-secondary-container': '#5c6a29',
        tertiary: '#c48a3f', /* Golden Ochre */
        'on-tertiary': '#ffffff',
        'tertiary-container': '#845409',
        'on-tertiary-container': '#ffd09c',
        background: '#fff8f4',
        'on-background': '#1f1b16',
        'surface-variant': '#ebe1d9',
        'canvas-parchment': '#FBF9F5',
        'surface-parchment-soft': '#F5F1E9',
        'surface-parchment-muted': '#EDE6DA',
        'card-pure': '#FFFFFF',
        'border-warm-subtle': '#E4DDD0',
        'border-warm-accent': '#D1C4AF',
        'water-azure': '#5588A3',
        'water-shallow': '#8EAFC2',
        'olive-deep': '#4C5B23',
        'terracotta-earth': '#B85D38',
        'desert-stone': '#8A7968',
      },
      fontFamily: {
        serif: ['Merriweather', 'serif'],
        sans: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      spacing: {
        'gutter': '1.5rem',
        'gutter-sm': '1rem',
        'gutter-lg': '2rem',
        'margin': '1.5rem',
        'margin-sm': '1rem',
        'margin-lg': '3rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
      },
      boxShadow: {
        'low': '0 2px 8px -2px rgba(43, 38, 33, 0.04), 0 4px 16px -4px rgba(43, 38, 33, 0.06)',
        'medium': '0 8px 24px -6px rgba(58, 99, 123, 0.08), 0 4px 12px -2px rgba(43, 38, 33, 0.05)',
        'high': '0 20px 40px -12px rgba(43, 38, 33, 0.16)',
      },
    },
  },
  plugins: [],
}
